### ISSUE TITLE
No rocks present at website

### ISSUE THREAD

**Issue by erikskaar** [FredrikAugust/fredrik.rocks#1]
The about section reads "A website for rock enthousiasts." which I find misleading as I visited the website and I could not find any pictures of rocks, nor any info about rocks.

**Comment by FredrikAugust** [comment]
Hello, @erikskaar

I am very sorry. 

Customer satisfaction is very important to me, and I hope a 110% refund will make you happy.

I will get to work on this as soon as possible.

Fredirk

**Comment by FredrikAugust** [comment]
May this be a CSS bug? What's your browser version?

**Comment by erikskaar** [comment]
My current version is `83.0.4103.106`, but the bug seemed to be present on other versions as well.

**Comment by FredrikAugust** [comment]
Very strange! 🪨

**Comment by FredrikAugust** [comment]
Sorry for the delay.

**Comment by erikskaar** [comment]
THERE ARE STILL NO ROCKS!

**Comment by blauks** [comment]
I am experiencing the same issue, is there an ETA on this?

**Comment by FredrikAugust** [comment]
I am SO sorry, @blauks and @erikskaar. Let me talk to my development team, they are called the Bromstad Billionaires.

ETA today.

**Comment by blauks** [comment]
Hey man, it's fine. But I do think we should talk about this on the annual fredrik.rocks board meeting.

**Comment by FredrikAugust** [comment]
> Hey man, it's fine. But I do think we should talk about this on the annual fredrik.rocks board meeting.

Sorry for the late resolution. I believe the issue has been resolved now. Can you confirm, @erikskaar and @blauks?

**Comment by blauks** [comment]
http://i.imgur.com/pfTO3ZV.png
